-- Rollback-only integration/security tests. Run as database owner with ON_ERROR_STOP.
begin;
create function pg_temp.assert_true(ok boolean,label text) returns void language plpgsql as $$
begin if ok is distinct from true then raise exception 'FAIL: %',label; end if; end;
$$;
create function pg_temp.denied(statement text) returns void language plpgsql as $$
begin
 begin execute statement; exception when others then return; end;
 raise exception 'FAIL: unexpectedly allowed: %',statement;
end;
$$;
update public.ads set status='paused';
insert into auth.users(id,email,raw_user_meta_data)
select ('e1000000-0000-0000-0000-'||lpad(n::text,12,'0'))::uuid,'ads-test-'||n||'@example.test',jsonb_build_object('username','ads_test_'||n,'dob','1980-01-01') from generate_series(1,4)n;
update public.profiles set role=case id::text when 'e1000000-0000-0000-0000-000000000002' then 'moderator' when 'e1000000-0000-0000-0000-000000000003' then 'admin' else 'ceo' end where id in ('e1000000-0000-0000-0000-000000000002','e1000000-0000-0000-0000-000000000003','e1000000-0000-0000-0000-000000000004');
create temporary table fixture(id uuid);
grant select,insert on fixture to authenticated;
select set_config('request.jwt.claim.sub','e1000000-0000-0000-0000-000000000003',true);
set local role authenticated;
insert into fixture select public.save_ad_campaign('{"name":"Eligible","advertiser_name":"TriggerFeed","advertiser_type":"house","status":"active","destination_url":"https://triggerfeed.com/merch"}',
 '{"headline":"All","body":"Example","platform":"all","call_to_action":"Shop"}','{"frequency":7,"weight":1,"enabled":true}');
select pg_temp.assert_true((public.get_admin_ads_dashboard()->'summary'->>'active_campaigns')::int=1,'admin dashboard');
select pg_temp.denied($q$select public.save_ad_campaign('{"name":"Unsafe","advertiser_name":"Bad","advertiser_type":"house","status":"active","destination_url":"javascript:alert(1)"}','{"headline":"Bad","platform":"all","call_to_action":"Go"}','{}')$q$);
reset role;
insert into public.ad_creatives(ad_id,headline,platform,call_to_action) select fixture.id,p,p,'Shop' from fixture cross join unnest(array['web_desktop','web_mobile','android']) p;
create temporary table tickets as select * from public.get_feed_ads('web_desktop',p_limit=>0);
grant select,insert,delete on tickets to anon,authenticated;
select set_config('request.jwt.claim.sub','',true);
set local role anon;
select pg_temp.denied('select * from public.ad_impressions');
select pg_temp.denied('select * from public.ad_clicks');
select pg_temp.denied('select public.get_admin_ads_dashboard()');
select pg_temp.denied($q$select public.save_ad_campaign('{}','{}','{}')$q$);
select pg_temp.denied($q$select public.get_feed_ads('web')$q$);
insert into tickets select * from public.get_feed_ads('web_desktop',p_limit=>1);
insert into tickets select * from public.get_feed_ads('web_mobile',p_limit=>1);
insert into tickets select * from public.get_feed_ads('android',p_limit=>1);
select pg_temp.assert_true((select count(*)=3 and bool_and(headline=platform) from tickets),'platform-specific creatives preferred over all');
reset role;
select pg_temp.assert_true(not exists(select 1 from public.ad_impressions),'fetch creates no impressions');
select pg_temp.assert_true(not exists(select 1 from public.ad_clicks),'fetch creates no clicks');
set local role anon;
select pg_temp.assert_true(public.record_ad_event((select delivery_id from tickets where platform='web_desktop'),'impression'),'anonymous visible impression');
select pg_temp.assert_true(not public.record_ad_event((select delivery_id from tickets where platform='web_desktop'),'impression'),'impression deduplicated');
select pg_temp.assert_true(public.record_ad_event((select delivery_id from tickets where platform='web_desktop'),'click'),'anonymous click');
select pg_temp.assert_true(not public.record_ad_event((select delivery_id from tickets where platform='web_desktop'),'click'),'click deduplicated');
select pg_temp.assert_true(not public.record_ad_event(gen_random_uuid(),'impression'),'fabricated ticket rejected');
select pg_temp.denied($q$insert into public.ad_clicks(delivery_id,ad_id,creative_id,platform,placement) select delivery_id,ad_id,creative_id,platform,placement from tickets limit 1$q$);
reset role;
select set_config('request.jwt.claim.sub','e1000000-0000-0000-0000-000000000001',true);
set local role authenticated;
select pg_temp.assert_true((select count(*)=0 from public.ads),'member cannot browse campaign administration');
select pg_temp.assert_true((select count(*)=0 from public.ad_impressions),'member cannot browse analytics');
select pg_temp.denied('select public.get_admin_ads_dashboard()');
select pg_temp.denied($q$select public.set_ad_status((select id from fixture),'ended')$q$);
select pg_temp.assert_true(not public.record_ad_event((select delivery_id from tickets where platform='android'),'impression'),'ticket bound to original identity');
delete from tickets;
insert into tickets select * from public.get_feed_ads('android',p_limit=>1);
select pg_temp.assert_true(public.record_ad_event((select delivery_id from tickets),'impression'),'member tracking succeeds');
reset role;
select set_config('request.jwt.claim.sub','e1000000-0000-0000-0000-000000000002',true);
set local role authenticated;
select pg_temp.denied('select public.get_admin_ads_dashboard()');
select pg_temp.denied($q$select public.save_ad_campaign('{}','{}','{}')$q$);
select pg_temp.assert_true((select count(*)=0 from public.ad_clicks),'moderator cannot read analytics');
reset role;
select set_config('request.jwt.claim.sub','e1000000-0000-0000-0000-000000000004',true);
set local role authenticated;
select pg_temp.assert_true(public.get_admin_ads_dashboard() is not null,'CEO dashboard allowed');
select public.set_ad_status((select id from fixture),'paused');
select pg_temp.assert_true((select count(*)=0 from public.get_feed_ads('android')),'paused excluded');
select public.set_ad_status((select id from fixture),'ended');
select pg_temp.assert_true((select count(*)=0 from public.get_feed_ads('android')),'ended excluded');
select public.set_ad_status((select id from fixture),'draft');
select pg_temp.assert_true((select count(*)=0 from public.get_feed_ads('android')),'draft excluded');
select public.set_ad_status((select id from fixture),'active');
reset role;
update public.ads set starts_at=now()+interval '1 day' where id=(select id from fixture);
select pg_temp.assert_true((select count(*)=0 from public.get_feed_ads('android')),'future excluded');
update public.ads set starts_at=now()-interval '2 days',ends_at=now()-interval '1 day' where id=(select id from fixture);
select pg_temp.assert_true((select count(*)=0 from public.get_feed_ads('android')),'expired excluded');
update public.ads set starts_at=null,ends_at=null where id=(select id from fixture);
update public.ad_placements set enabled=false where ad_id=(select id from fixture);
select pg_temp.assert_true((select count(*)=0 from public.get_feed_ads('android')),'disabled placement excluded');
update public.ad_placements set enabled=true where ad_id=(select id from fixture);
delete from public.ad_creatives where ad_id=(select id from fixture) and platform in ('all','android');
select pg_temp.assert_true((select count(*)=0 from public.get_feed_ads('android')),'incompatible creative excluded');
select pg_temp.assert_true((select count(*)=1 from public.get_feed_ads('web_mobile',p_limit=>1)),'compatible mobile web retained');
select set_config('request.jwt.claim.sub','',true);
delete from tickets;
insert into tickets select * from public.get_feed_ads('web_mobile',p_limit=>1);
update public.ad_deliveries set expires_at=now()-interval '1 second';
set local role anon;
select pg_temp.assert_true(not public.record_ad_event((select delivery_id from tickets where platform='web_mobile'),'impression'),'expired ticket rejected');
reset role;
rollback;
