import {
  Home,
  Users,
  SquarePlus,
  Bell,
  User,
  Menu,
  Settings,
  LogOut,
  Pencil,
  Trash2,
  MessageCircle,
  MessageSquare,
  Image,
  Video,
  Camera,
  Search,
  Send,
  Flag,
  Heart,
  MoreHorizontal,
  X,
  ChevronLeft,
  ChevronRight,
  Check,
  CircleAlert,
  ThumbsDown,
  ThumbsUp,
} from "lucide-react";

export const icons = {
  home: Home,
  friends: Users,
  create: SquarePlus,
  notifications: Bell,
  profile: User,
  menu: Menu,
  settings: Settings,
  logout: LogOut,
  edit: Pencil,
  delete: Trash2,
  post: Send,
  comment: MessageCircle,
  reply: MessageSquare,
  image: Image,
  video: Video,
  camera: Camera,
  search: Search,
  report: Flag,
  like: Heart,
  more: MoreHorizontal,
  close: X,
  back: ChevronLeft,
  next: ChevronRight,
  check: Check,
  warning: CircleAlert,
  thumbsdown: ThumbsDown,
  thumbsup: ThumbsUp,
};