import {
  AtSign,
  Bell,
  BellCheck,
  BellDot,
  Camera,
  Check,
  ChevronLeft,
  ChevronRight,
  CircleAlert,
  Crosshair,
  Flag,
  Handshake,
  Heart,
  Home,
  Image,
  LogOut,
  Megaphone,
  Menu,
  MessageCircle,
  MessageSquare,
  MoreHorizontal,
  Pencil,
  Pin,
  Search,
  Send,
  Settings,
  ShieldAlert,
  SquarePlus,
  ThumbsDown,
  ThumbsUp,
  Trash2,
  User,
  UserCheck,
  UserPlus,
  Users,
  Video,
  X,
} from "lucide-react";

export const icons = {
  announcement: Megaphone,
  atsign: AtSign,
  back: ChevronLeft,
  camera: Camera,
  check: Check,
  close: X,
  comment: MessageCircle,
  create: SquarePlus,
  crosshair: Crosshair,
  delete: Trash2,
  edit: Pencil,
  friends: Users,
  handshake: Handshake,
  home: Home,
  image: Image,
  like: Heart,
  logout: LogOut,
  mention: AtSign,
  menu: Menu,
  more: MoreHorizontal,
  next: ChevronRight,
  notifications: Bell,
  notificationsDot: BellDot,
  notificationsUnread: BellCheck,
  pin: Pin,
  post: Send,
  profile: User,
  reply: MessageSquare,
  report: Flag,
  search: Search,
  settings: Settings,
  shieldAlert: ShieldAlert,
  stickyPost: Pin,
  thumbsdown: ThumbsDown,
  thumbsup: ThumbsUp,
  usercheck: UserCheck,
  userplus: UserPlus,
  video: Video,
  warning: CircleAlert,
};