import { Black_Ops_One, Tomorrow } from "next/font/google";
import { createClient } from "@/lib/supabase/server";
import AppHeader from "@/components/layout/AppHeader";
import BottomNav from "@/components/navigation/BottomNav";
import { Toaster } from "react-hot-toast";
import "@/styles/globals.scss";

const blackOpsOne = Black_Ops_One({
  weight: "400",
  subsets: ["latin"],
  variable: "--font-brand",
});

const tomorrow = Tomorrow({
  weight: ["400", "500", "600", "700"],
  subsets: ["latin"],
  variable: "--font-body",
});

export const metadata = {
  title: "TriggerFeed",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
  const supabase = await createClient();

  const {
    data: { user },
  } = await supabase.auth.getUser();

  let unreadNotifications = 0;

  if (user) {
    const { count } = await supabase
      .from("notifications")
      .select("id", { count: "exact", head: true })
      .eq("user_id", user.id)
      .eq("is_read", false)
      .is("dismissed_at", null);

    unreadNotifications = count ?? 0;
  }
  return (
    <html lang="en" className={`${blackOpsOne.variable} ${tomorrow.variable}`}>
      <body>
        <AppHeader />
        <div className="content">
          {children}
        </div>
        <Toaster position="bottom-center" />
        {user ? (
          <BottomNav unreadNotifications={unreadNotifications} />
        ) : null}
        <footer>footer</footer>
      </body>
    </html>
  );
}
