import { Black_Ops_One, Tomorrow } from "next/font/google";
import AppNav from "@/components/layout/AppNav";
import "@/styles/globals.scss";

const blackOpsOne = Black_Ops_One({
  weight: "400",
  subsets: ["latin"],
  variable: "--font-brand",
});

const tomorrow = Tomorrow({
  weight: ["400", "500", "600", "700"],
  subsets: ["latin"],
  variable: "--font-body",
});

export const metadata = {
  title: "TriggerFeed",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={`${blackOpsOne.variable} ${tomorrow.variable}`} style={{ padding: ".5rem", maxWidth: "620px", margin: "0 auto" }}>
      <body>
        <AppNav />
        {children}
      </body>
    </html>
  );
}
